apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
commonLabels:
  variant: production
resources:
  - ../../base
  - job.yaml
  - secret.yaml
patchesStrategicMerge:
  - patch.yaml

vars:
  - name: MYSQL_SERVICE
    objref:
      kind: Service
      name: mysql
      apiVersion: v1
